package dev.abarmin.telegram.collector.service;

public enum ChatState {
    STARTED,

    COLLECTION_CREATION,
    COLLECTION_RENAMING,
    COLLECTION_DELETING,

    COLLECTION_ITEM_CREATION,
    COLLECTION_ITEM_RENAMING,
    COLLECTION_ITEM_DELETING,
    COLLECTION_ITEM_ADDING_PHOTO,
    COLLECTION_ITEM_SEARCHING,
}
