version: '3.9'

services:

  db:
    image: mariadb:10.11
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MYSQL_DATABASE=collector_bot
      - MYSQL_USER=collector_bot
      - MYSQL_PASSWORD=collector_bot

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1