CREATE TABLE IF NOT EXISTS `USERS` (
  `ID` INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (`ID`),
  `CHAT_ID` INT NOT NULL,
  `USERNAME` VARCHAR(255) NOT NULL,
  `STATE` VARCHAR(255) NOT NULL,
  `CONTEXT` TEXT NULL
);