CREATE TABLE IF NOT EXISTS `COLLECTION_ITEMS` (
  `ID` INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (`ID`),
  `COLLECTION_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `IMAGE_FILE_ID` VARCHAR(255) NULL
);