CREATE TABLE IF NOT EXISTS `COLLECTION_ACCESS` (
  `ID` INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (`ID`),
  `COLLECTION_ID` INT NOT NULL,
  `OWNER_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  `PERMISSIONS` VARCHAR(255) NOT NULL
);