ALTER TABLE `COLLECTION_ACCESS`
ADD FOREIGN KEY (`COLLECTION_ID`) REFERENCES `COLLECTIONS` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `COLLECTION_ACCESS`
ADD FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `COLLECTION_ACCESS`
ADD FOREIGN KEY (`OWNER_ID`) REFERENCES `USERS` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;