CREATE TABLE IF NOT EXISTS `COLLECTION_SHARE_CODES` (
  `ID` INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (`ID`),
  `COLLECTION_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  `CODE` VARCHAR(255) NOT NULL,
  `ACCESS_LEVEL` VARCHAR(255) NOT NULL,
  `ACCESS_LINK` VARCHAR(255) NOT NULL,
  `IS_VALID` BOOLEAN,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `VALID_BEFORE` TIMESTAMP NOT NULL
);

ALTER TABLE `COLLECTION_SHARE_CODES`
ADD FOREIGN KEY (`COLLECTION_ID`) REFERENCES `COLLECTIONS` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `COLLECTION_SHARE_CODES`
ADD FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;